function sys = mylinearizemodel(op)
% MYLINEARIZEMODEL Linearize the Simulink model - tenzo6dof.
%
% SYS = MYLINEARIZE(OP) linearizes the Simulink model tenzo6dof about
% the operating point OP.

% MATLAB(R) file generated by MATLAB(R) 7.14 and Simulink Control Design (TM) 3.5.
%
% Generated on: 02-Jun-2014 03:18:35

%% Specify the model name
model = 'tenzo6dof';

%% Create the linearization I/O as specified in tenzo6dof
ios(2) = linio('tenzo6dof/Tenzo',1,'out','on');
ios(1) = linio('tenzo6dof/Coppie',1,'in');

%% Linearize the model
sys = linearize(model,op,ios);

%% Plot the resulting linearization.
bode(sys)
